version: 0.2
phases:
  pre_build:
    commands:
      - echo "Inside pre_build"
  build:
    commands:
      - echo "Inside build"
      - mvn clean install
  post_build:
    commands:
      - echo "Inside post_build.."
artifacts:
  files:
    - target/spring-aws-demo.jar